#!/bin/bash
git pull
git add .  #添加当前目录下的所有文件和子目录
#git add  -A # in git 2.0
git commit -m  "`date`"  #"dbbak and cutnglog"
git push  origin master 
#git push 
#有时记得要删除
#   （使用 "git add/rm <file>..." 更新要提交的内容）
#   （使用 "git checkout -- <file>..." 丢弃工作区的改动）
#修改尚未加入提交（使用 "git add" 和/或 "git commit -a"）

