BEGIN TRANSACTION;
CREATE TABLE "mysite_maker" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(10) NOT NULL, "country" varchar(10) NOT NULL);
INSERT INTO `mysite_maker` VALUES (1,'ASUS','Taiwan');
INSERT INTO `mysite_maker` VALUES (2,'HTC','Taiwan');
INSERT INTO `mysite_maker` VALUES (3,'SONY','Japan');
INSERT INTO `mysite_maker` VALUES (4,'Apple','USA');
INSERT INTO `mysite_maker` VALUES (5,'Nokia','Finland');
INSERT INTO `mysite_maker` VALUES (6,'Infocus','Taiwan');
INSERT INTO `mysite_maker` VALUES (7,'Samsung','Korea');
CREATE INDEX "mysite_product_6e1be4b4" ON "mysite_product" ("pmodel_id");
CREATE INDEX "mysite_pphoto_9bea82de" ON "mysite_pphoto" ("product_id");
CREATE INDEX "mysite_pmodel_8e8bc641" ON "mysite_pmodel" ("maker_id");
CREATE INDEX "django_session_de54fa62" ON "django_session" ("expire_date");
CREATE INDEX "django_admin_log_e8701ad4" ON "django_admin_log" ("user_id");
CREATE INDEX "django_admin_log_417f1b1c" ON "django_admin_log" ("content_type_id");
CREATE INDEX "auth_user_user_permissions_e8701ad4" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_8373b171" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "auth_user_groups_e8701ad4" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_0e939a4f" ON "auth_user_groups" ("group_id");
CREATE INDEX "auth_permission_417f1b1c" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_permissions_8373b171" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_group_permissions_0e939a4f" ON "auth_group_permissions" ("group_id");
COMMIT;
