BEGIN TRANSACTION;
CREATE TABLE "mysite_pmodel" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "maker_id" integer NOT NULL REFERENCES "mysite_maker" ("id"), "url" varchar(200) NOT NULL, "name" varchar(20) NOT NULL);
INSERT INTO `mysite_pmodel` VALUES (1,5,'http://www.sogi.com.tw/products/NOKIA_5800_XpressMusic/4464','XM 5800');
INSERT INTO `mysite_pmodel` VALUES (2,1,'https://www.asus.com/tw/Phone/ZenFone_2_ZE551ML/','Zenfone 2');
INSERT INTO `mysite_pmodel` VALUES (3,6,'http://www.infocusphone.com/tw/product/M370/','M370');
INSERT INTO `mysite_pmodel` VALUES (4,7,'http://www.samsung.com/hk/consumer/mobile/mobile-phones/smartphone/GT-S7562UWATGY','DUOS');
INSERT INTO `mysite_pmodel` VALUES (5,3,'http://store.sony.com.tw/product/LT29i','Xperia TX');
INSERT INTO `mysite_pmodel` VALUES (6,7,'http://www.eprice.com.tw/mobile/intro/c01-p4555-samsung-galaxy-s3-16gb/','S3');
INSERT INTO `mysite_pmodel` VALUES (7,3,'http://www.sonymobile.com/tw/products/phones/xperia-z3/','Xperia Z3');
CREATE INDEX "mysite_product_6e1be4b4" ON "mysite_product" ("pmodel_id");
CREATE INDEX "mysite_pphoto_9bea82de" ON "mysite_pphoto" ("product_id");
CREATE INDEX "mysite_pmodel_8e8bc641" ON "mysite_pmodel" ("maker_id");
CREATE INDEX "django_session_de54fa62" ON "django_session" ("expire_date");
CREATE INDEX "django_admin_log_e8701ad4" ON "django_admin_log" ("user_id");
CREATE INDEX "django_admin_log_417f1b1c" ON "django_admin_log" ("content_type_id");
CREATE INDEX "auth_user_user_permissions_e8701ad4" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_8373b171" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "auth_user_groups_e8701ad4" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_0e939a4f" ON "auth_user_groups" ("group_id");
CREATE INDEX "auth_permission_417f1b1c" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_permissions_8373b171" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_group_permissions_0e939a4f" ON "auth_group_permissions" ("group_id");
COMMIT;
